version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Starting build
          command: gradle build
      - run:
          name: Starting unit test.
          command: gradle test
