version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-ea-jdk-browsers
    steps:
      - run:
          name: Starting build
          command: mkdir -p /home/circleci/project/build/cobertura/main
          command: touch /home/circleci/project/build/cobertura/main/cobertura-test.ser
          command: chmod +x ./gradlew;./gradlew clean build
      - run:
          name: Starting unit test.
          command: chmod +x ./gradlew;./gradlew clean test
