version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-ea-jdk-browsers
    steps:
      - checkout
      - run:
          name: Starting build
          command: chmod +x ./gradlew;./gradlew clean build -x test
  test:
    docker:
      - image: circleci/openjdk:10-ea-jdk-browsers
    steps:
      - checkout
      - run:
          name: Starting unit test.
          command: chmod +x ./gradlew;./gradlew --info clean test jacocoTestReport coveralls
workflows:
  version: 2
  build_and_unit_test_workflow:
  jobs:
      - build
      - test
