version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-ea-jdk-browsers
    steps:
      - checkout
      - run:
          name: Starting build
          command: ./gradle build
      - run:
          name: Starting unit test.
          command: ./gradle test
